name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Poetry
      run: pipx install poetry==1.3.2
    - name: Build
      run: poetry build
    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
    - name: Run export
      run: |
        poetry install
        poetry run python src/rank_comparia/export.py || true
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
    - name: Upload outputs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: outputs
        path: output/
        if-no-files-found: ignore